### PR TITLE
docs: updated to include a new way to break down start/stop

### PR DESCRIPTION
**Pull request by ethanholz**
This PR aims to improve upon the lack of clear guidance on what is required for "start" vs "stop" actions related to #8.

### CODE REVIEW

**Comment by ethanholz** [comment]
@dwhswenson looking for guidance on if this is a bit clearer of an image around what is uses in which action. Open to improvements!

**Review by dwhswenson — COMMENTED** [review]
Would it make sense to change these such that the "required" columns under start/stop became "required for start" / "required for stop"? There are things marked as not required, which, now that the sections are nicely separated like this, might be misleading. (Basically anything that says, e.g., "will not start if not specified")

Similarly, there could be some clarification that the `instance_mapping` is the same as the output generated by the `start` process, and a clarification under Outputs that this is only an output from the `start` process.

A few changes, but I like this overall approach to make it clearer. I think this is already an improvement.

**Comment by ethanholz** [comment]
Agreed, more than happy to add these additions for clarity!

**Comment by ethanholz** [comment]
Added some new areas for clarity. The CI probably shouldn't update unless we are actively updating code, `codecov` and `pytest` runs are not necessary when updating docs alone.

**Review by dwhswenson — APPROVED** [review]
LGTM!

**Pull request merged**
