### PR TITLE
test: Moves openmm-gpu-test into this repo

### PR DESCRIPTION
**Pull request by ethanholz**
Moves and (slightly) modifies the code from [omsf-eco-infra/openmm-gpu-test](https://github.com/omsf-eco-infra/openmm-gpu-test) into this repo. I have added the IAM role as a secret so it is easier to do testing in the future and it is already added to the repo.

### CODE REVIEW

**Comment by ethanholz** [comment]
Closes #34

**Comment by ethanholz** [comment]
@dwhswenson this is ready for review and has all the pieces in place for running multiple tests!

**Comment by ethanholz** [comment]
One thing to note, our previous PR #24, had the initial staging for CI docs (specifically a test plan). We may want to consider splitting docs for CI into its own PR that is separate from that PR.

**Review by dwhswenson — APPROVED** [review]
LGTM (since I've seen it in action in the original repo). Let's merge this in! We'll probably need to add docs about handling a build matrix soon, too.

**Pull request merged**
